"""add image_path to products

Revision ID: 286e8f20dff8
Revises: 470dca3fb9be
Create Date: 2025-05-24 21:09:22.958991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "286e8f20dff8"
down_revision: Union[str, None] = "470dca3fb9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("image_path", sa.String(), nullable=False, server_default=""),
    )
    op.alter_column("products", "stock", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("products", "available")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("available", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.alter_column("products", "stock", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("products", "image_path")
    # ### end Alembic commands ###
