"""add whatsapp to clients

Revision ID: 7034fbe2fbfd
Revises: cd1cc4806a73
Create Date: 2025-05-25 05:12:12.330203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7034fbe2fbfd"
down_revision: Union[str, None] = "cd1cc4806a73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_products_id"), table_name="order_products")
    op.drop_table("order_products")
    op.add_column("clients", sa.Column("whatsapp_number", sa.String(), nullable=True))
    op.drop_index(op.f("ix_clients_whatsapp"), table_name="clients")
    op.create_index(
        op.f("ix_clients_whatsapp_number"), "clients", ["whatsapp_number"], unique=False
    )
    op.drop_column("clients", "whatsapp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column("whatsapp", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_clients_whatsapp_number"), table_name="clients")
    op.create_index(op.f("ix_clients_whatsapp"), "clients", ["whatsapp"], unique=False)
    op.drop_column("clients", "whatsapp_number")
    op.create_table(
        "order_products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("order_products_order_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("order_products_product_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_products_pkey")),
    )
    op.create_index(
        op.f("ix_order_products_id"), "order_products", ["id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("orders_client_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("orders_created_by_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###
